### PR TITLE
Add locationId

### PR DESCRIPTION
**Pull request by alexpablo**
Add locationId to search from new getLocation functions.

### CODE REVIEW

**Comment by raiym** [comment]
Thank you for contribution. 

Changes in InstagramScraper.php is great. 

But I with locationId there is issues. Because it is not presented in response. 

For example if you go to and check medias where location is not null you will not see location id, only location name.

**Comment by raiym** [comment]
@alexpablo

**Comment by raiym** [comment]
It will be grate if you remove Media updates

**Comment by alexpablo** [comment]
Github not permit to modify the code! Always say a error :S

On a photo https://www.instagram.com/p/BF_63o-oxc0/ obtain an array thas
contain location id:
"location": {"has_public_page": true, "id": "216220278", "name": "Lago
Nahuel Huapi"}}}]}

I modify the code: but Github not permit to upload:
if (isset($mediaArray['location']['id'])) { $instance->locationId =
$mediaArray['location']['id']; }


2016-07-12 18:10 GMT+02:00 Raiymbek Kapishev <notifications@github.com>:

**Comment by raiym** [comment]
I see. No worries. I'll merge and delete only row in fromApi() method

**Comment by raiym** [comment]
Do you know what has_public_page is?

**Comment by alexpablo** [comment]
I've been searching and have not found anything :-(

**Comment by raiym** [comment]
I see

**Pull request merged**
